### ISSUE TITLE
is it possible to make ContactPerson be invalid without email?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandischema#189]
We have https://github.com/dandisets/000108/blob/draft/dandiset.yaml where contact person is Lee , but he is listed without email.

```yaml
- affiliation: []
  includeInCitation: true
  name: Kamentsky, Lee
  roleName:
  - dcite:ContactPerson
  schemaKey: Person
- affiliation: []
  email: smarx@mit.edu
  identifier: 0000-0002-8209-0059
  includeInCitation: true
  name: Marx, Slayton
  roleName:
  - dcite:DataManager
  - dcite:DataCurator
  - dcite:Investigation
  - dcite:ProjectMember
  - dcite:Researcher
  - dcite:Software
  - dcite:Supervision
  - dcite:Visualization
  schemaKey: Person
```

PS I now made @slaytonmarx to be the contact person since AFAIK Lee is no longer with the project. Please adjust if that is not true
